# ==============================================================================
# Merged Lakeflow Source: hacker_news
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import datetime, timezone
from decimal import Decimal
from typing import (
    Any,
    Iterator,
    Optional,
    Sequence,
)
import json
import time

from pyspark.sql import Row
from pyspark.sql.datasource import (
    DataSource,
    DataSourceReader,
    DataSourceStreamReader,
    InputPartition,
    SimpleDataSourceStreamReader,
)
from pyspark.sql.streaming.datasource import ReadAllAvailable, SupportsTriggerAvailableNow
from pyspark.sql.types import (
    ArrayType,
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    DoubleType,
    FloatType,
    IntegerType,
    LongType,
    MapType,
    StringType,
    StructField,
    StructType,
    TimestampType,
    VariantType,
    VariantVal,
)
import base64
import concurrent.futures
import requests


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:  # pylint: disable=too-many-return-statements
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle VariantType
        if isinstance(field_type, VariantType):
            return VariantVal.parseJson(value) if isinstance(value, str) else value

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_partition.py
    ########################################################

    class SupportsPartition(ABC):
        """Mixin for connectors that support partitioned reads across Spark executors.

        Must be used together with LakeflowConnect. Implement this when your
        connector can split work into partitions that Spark distributes to workers,
        instead of reading all data in one partition batch.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartition):
                ...
        """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """

        @abstractmethod
        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Read records for a single partition.

            This method runs on Spark executors and must be self-contained.

            Args:
                table_name: The name of the table.
                partition: One of the partition dicts returned by
                    :meth:`get_partitions`.
                table_options: A dictionary of options for accessing the table.
            Returns:
                An iterator of records as JSON-compatible dicts.
            """


    class SupportsPartitionedStream(SupportsPartition):
        """Mixin for connectors that support partitioned streaming reads.

        Extends :class:`SupportsPartition` with offset awareness for streaming
        micro-batches. A connector implementing this mixin automatically supports
        both partitioned batch reads (via the inherited interface) and partitioned
        streaming reads.

        Usage::

            class MyConnector(LakeflowConnect, SupportsPartitionedStream):
                ...
        """

        def is_partitioned(self, table_name: str) -> bool:
            """Return whether the given table supports partitioned streaming.

            The default returns True. Override to return False for tables that
            should fall back to simpleStreamReader.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
            """
            return True

        @abstractmethod
        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the most recent offset available for the table.

            Called by Spark on every micro-batch to discover new data.

            Micro-batch sizing (by row count, time window, etc.) is entirely the
            connector's responsibility — use table_options (e.g. ``window_days``,
            ``max_records_per_batch``) to control it.  The framework always
            requests "all available" and does not pass an admission-control
            hint here.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The current committed offset.  ``{}`` on the very
                    first call (from ``initialOffset``), then the last returned
                    end_offset on each subsequent call.
            Returns:
                A dict whose keys and values are primitive types (str, int, bool).
            """

        @abstractmethod
        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> Sequence[dict]:
            """Return partition descriptors for reading data.

            Each returned dict is passed to :meth:`read_partition` on an executor.

            For batch reads, ``start_offset`` and ``end_offset`` are both None —
            return partitions covering the entire table.

            For streaming micro-batches, they delimit the offset range — return
            partitions covering that range, or an empty sequence when
            ``start_offset == end_offset``.

            Args:
                table_name: The name of the table.
                table_options: A dictionary of options for accessing the table.
                start_offset: The start offset (exclusive), or None for batch.
                end_offset: The end offset (inclusive), or None for batch.
            Returns:
                A sequence of partition descriptor dicts. Each dict must be
                JSON-serialisable (primitive types only).
            """


    ########################################################
    # src/databricks/labs/community_connector/interface/supports_namespaces.py
    ########################################################

    class SupportsNamespaces(ABC):
        """Mixin for connectors whose tables live under hierarchical namespaces.

        A namespace is a path of zero or more string segments (e.g. ``["org",
        "repo"]`` for GitHub, ``["tenant", "project"]`` for Azure DevOps).
        Connectors with a flat catalog do not need this mixin — the framework
        falls back to :meth:`LakeflowConnect.list_tables` and reports each table
        with an empty namespace.

        Output ordering on the ``_community_namespaces`` and ``_community_tables``
        Spark virtual tables is normalized by the framework via ``sorted(...)``,
        so connector implementations of :meth:`list_namespaces` and
        :meth:`list_tables_in_namespace` are free to return their results in
        any order (including from a :class:`set` or generator).

        Must be used together with :class:`LakeflowConnect`.

        Usage::

            class MyConnector(LakeflowConnect, SupportsNamespaces):
                ...
        """

        @abstractmethod
        def list_namespaces(
            self,
            prefix: list[str] | None = None,
        ) -> list[list[str]]:
            """Return the immediate child namespaces under ``prefix``.

            This method returns one level of *namespace* children only — it
            never returns tables. A namespace can hold tables and child
            namespaces independently; callers must always call
            :meth:`list_tables_in_namespace` for every namespace they care
            about, regardless of whether :meth:`list_namespaces` returned
            children for it. An empty return value just means there are no
            further child namespaces under ``prefix``.

            Walk the full tree by recursing on each returned child.

            Args:
                prefix: A namespace path under which to list children. ``None`` or
                    an empty list lists the root-level namespaces.
            Returns:
                A list of full namespace paths (each path includes the prefix).
            """

        @abstractmethod
        def list_tables_in_namespace(
            self,
            namespace: list[str],
        ) -> list[str]:
            """Return the table names that live directly under ``namespace``.

            Callers that want every table across the whole catalog walk the
            namespace tree via :meth:`list_namespaces` and call this method
            once per leaf — there is no "list everything" shortcut.

            Args:
                namespace: The namespace path. An empty list ``[]`` selects
                    root-level tables (those that live outside any namespace).
            Returns:
                A list of table names. The full ``(namespace, table_name)``
                row exposed on ``_community_tables`` is reconstructed by the
                framework from the namespace the caller already supplied, so
                the connector does not need to echo it back.
            """


    ########################################################
    # src/databricks/labs/community_connector/sources/hacker_news/hacker_news_schemas.py
    ########################################################

    ITEMS_TABLE = "items"
    UPDATES_TABLE = "updates"
    TOPSTORIES_TABLE = "topstories"
    NEWSTORIES_TABLE = "newstories"
    BESTSTORIES_TABLE = "beststories"

    STORY_LIST_TABLES = (TOPSTORIES_TABLE, NEWSTORIES_TABLE, BESTSTORIES_TABLE)

    # Map each story-list table to its endpoint path segment.
    STORY_LIST_ENDPOINTS = {
        TOPSTORIES_TABLE: "topstories",
        NEWSTORIES_TABLE: "newstories",
        BESTSTORIES_TABLE: "beststories",
    }

    TABLES = [
        ITEMS_TABLE,
        UPDATES_TABLE,
        TOPSTORIES_TABLE,
        NEWSTORIES_TABLE,
        BESTSTORIES_TABLE,
    ]

    # ---- item schema -----------------------------------------------------------
    # Every item carries ``id`` and ``type``; all other fields are type-conditional
    # and may be absent. Absent struct fields are emitted as ``None`` (never {}),
    # and the raw parsed JSON is returned from read_table — the framework coerces
    # types per this schema.
    ITEM_SCHEMA = StructType(
        [
            StructField("id", LongType(), nullable=False),
            StructField("type", StringType(), nullable=True),
            StructField("by", StringType(), nullable=True),
            StructField("time", LongType(), nullable=True),  # unix seconds
            StructField("deleted", BooleanType(), nullable=True),
            StructField("dead", BooleanType(), nullable=True),
            StructField("title", StringType(), nullable=True),
            StructField("url", StringType(), nullable=True),
            StructField("text", StringType(), nullable=True),
            StructField("score", LongType(), nullable=True),
            StructField("descendants", LongType(), nullable=True),
            StructField("kids", ArrayType(LongType()), nullable=True),
            StructField("parent", LongType(), nullable=True),
            StructField("poll", LongType(), nullable=True),
            StructField("parts", ArrayType(LongType()), nullable=True),
        ]
    )

    # ---- updates schema --------------------------------------------------------
    # A single snapshot row per run holding the two recent-changes arrays.
    UPDATES_SCHEMA = StructType(
        [
            StructField("items", ArrayType(LongType()), nullable=True),
            StructField("profiles", ArrayType(StringType()), nullable=True),
            # ISO-8601 timestamp of the run that captured this snapshot.
            StructField("snapshot_time", StringType(), nullable=True),
        ]
    )

    # ---- story-list schema -----------------------------------------------------
    # One row per story id with its 0-based rank in the ranked list, plus the
    # snapshot timestamp of the run.
    STORY_LIST_SCHEMA = StructType(
        [
            StructField("story_id", LongType(), nullable=False),
            StructField("rank", LongType(), nullable=True),
            StructField("snapshot_time", StringType(), nullable=True),
        ]
    )

    TABLE_SCHEMAS = {
        ITEMS_TABLE: ITEM_SCHEMA,
        UPDATES_TABLE: UPDATES_SCHEMA,
        TOPSTORIES_TABLE: STORY_LIST_SCHEMA,
        NEWSTORIES_TABLE: STORY_LIST_SCHEMA,
        BESTSTORIES_TABLE: STORY_LIST_SCHEMA,
    }

    # ---- metadata --------------------------------------------------------------
    # items is the headline incremental (append) table; the cursor is the item id
    # high-water mark. The snapshot tables have no row-level primary key and no
    # cursor — they are fully re-read each run.
    TABLE_METADATA = {
        ITEMS_TABLE: {
            "primary_keys": ["id"],
            "cursor_field": "id",
            "ingestion_type": "append",
        },
        UPDATES_TABLE: {
            "primary_keys": [],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        TOPSTORIES_TABLE: {
            "primary_keys": [],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        NEWSTORIES_TABLE: {
            "primary_keys": [],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
        BESTSTORIES_TABLE: {
            "primary_keys": [],
            "cursor_field": None,
            "ingestion_type": "snapshot",
        },
    }

    # ---- admission control / batching defaults --------------------------------
    # maxitem is ~42M, so a cold start must NOT read from id 0. On first run we
    # default the starting offset to (maxitem - DEFAULT_START_LOOKBACK); a user
    # can override with the ``start_item_id`` table option to backfill further.
    DEFAULT_START_LOOKBACK = 1000
    # Cap ids fetched per read_table / micro-batch call so each batch reads a
    # bounded id window: effective end = min(maxitem, start.max_id + this).
    DEFAULT_MAX_RECORDS_PER_BATCH = 10000
    # Number of ids each partition descriptor covers when fanning out a
    # micro-batch across executors.
    DEFAULT_PARTITION_SIZE = 1000
    # Bounded concurrency for per-id fetches within a single partition.
    DEFAULT_FETCH_CONCURRENCY = 16

    # ---- HTTP behaviour --------------------------------------------------------
    BASE_URL = "https://hacker-news.firebaseio.com/v0"
    REQUEST_TIMEOUT = 20  # seconds; every request must set an explicit timeout
    RETRIABLE_STATUS_CODES = {429, 500, 502, 503, 504}
    MAX_RETRIES = 5
    INITIAL_BACKOFF = 0.5  # seconds; doubled after each retry


    ########################################################
    # src/databricks/labs/community_connector/sources/hacker_news/hacker_news.py
    ########################################################

    class HackerNewsLakeflowConnect(LakeflowConnect, SupportsPartitionedStream):
        """LakeflowConnect implementation for the public Hacker News API."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            # No credentials of any kind — the API is fully public.
            self._base_url = options.get("base_url", BASE_URL).rstrip("/")
            # Snapshot the id high-water mark once so a trigger never chases
            # ids created after this instance was constructed. Resolved lazily
            # (the first time it is needed) so __init__ stays cheap and the
            # instance carries no eager network state.
            self._init_max_id_cache: Optional[int] = None

        # ------------------------------------------------------------------
        # HTTP helpers
        # ------------------------------------------------------------------
        def _new_session(self) -> requests.Session:
            """Create a fresh requests Session.

            Sessions are created per-call (and inside ``read_partition`` on
            executors) rather than stored on ``self`` so the connector instance
            stays picklable when Spark ships the reader to workers.
            """
            return requests.Session()

        def _get_json(self, session: requests.Session, path: str):
            """GET ``{base_url}{path}`` and return parsed JSON, retrying on 429/5xx.

            ``path`` must start with ``/`` (e.g. ``/maxitem.json``). Returns the
            decoded JSON value, which may be ``None`` for missing/gap item ids.
            """
            url = f"{self._base_url}{path}"
            backoff = INITIAL_BACKOFF
            resp = None
            for attempt in range(MAX_RETRIES):
                resp = session.get(url, timeout=REQUEST_TIMEOUT)
                if resp.status_code not in RETRIABLE_STATUS_CODES:
                    break
                if attempt < MAX_RETRIES - 1:
                    time.sleep(backoff)
                    backoff *= 2
            if resp is None or resp.status_code != 200:
                status = resp.status_code if resp is not None else "no response"
                raise RuntimeError(f"GET {url} failed with status {status}")
            return resp.json()

        def _fetch_maxitem(self, session: requests.Session) -> int:
            """Return the current ``maxitem`` high-water mark as an int."""
            value = self._get_json(session, "/maxitem.json")
            if value is None:
                raise RuntimeError("maxitem.json returned null")
            return int(value)

        def _init_max_id(self) -> int:
            """Init-time snapshot of ``maxitem`` (cached for this instance).

            This is the cap that guarantees Trigger.AvailableNow termination:
            ``latest_offset`` never exceeds it, so once the stream catches up the
            offset stops advancing.
            """
            if self._init_max_id_cache is None:
                session = self._new_session()
                try:
                    self._init_max_id_cache = self._fetch_maxitem(session)
                finally:
                    session.close()
            return self._init_max_id_cache

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------
        def list_tables(self) -> list[str]:
            """Static table set — the HN API has no discovery endpoint."""
            return list(TABLES)

        def _validate_table(self, table_name: str) -> None:
            if table_name not in TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. Supported tables: {TABLES}"
                )

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            self._validate_table(table_name)
            return TABLE_SCHEMAS[table_name]

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            self._validate_table(table_name)
            return dict(TABLE_METADATA[table_name])

        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Single-driver read path.

            Used for the snapshot tables (which opt out of partitioning via
            ``is_partitioned``) and as the sequential fallback for ``items`` when
            the framework reads a non-partitioned stream.
            """
            self._validate_table(table_name)
            if table_name == UPDATES_TABLE:
                return self._read_updates_snapshot(table_options)
            if table_name in STORY_LIST_TABLES:
                return self._read_story_list_snapshot(table_name, table_options)
            if table_name == ITEMS_TABLE:
                return self._read_items_sequential(start_offset, table_options)
            raise ValueError(f"Unhandled table '{table_name}'")

        # ------------------------------------------------------------------
        # SupportsPartitionedStream interface
        # ------------------------------------------------------------------
        def is_partitioned(self, table_name: str) -> bool:
            """Only ``items`` partitions; snapshot tables use simpleStreamReader."""
            return table_name == ITEMS_TABLE

        def latest_offset(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
        ) -> dict:
            """Return the end offset for the next micro-batch of ``items``.

            Lightweight metadata-only call: it determines *which* ids exist, not
            the records themselves. The returned ``max_id`` is bounded by
            ``max_records_per_batch`` (so each batch is a finite id window) and
            capped at the init-time ``maxitem`` snapshot (so the trigger
            terminates). When the start offset already sits at the snapshot, the
            same value is returned and Spark stops issuing micro-batches.
            """
            if table_name != ITEMS_TABLE:
                # Snapshot tables don't partition; offset machinery is unused.
                return {}

            init_max = self._init_max_id()
            max_records = self._max_records_per_batch(table_options)

            start_max_id = self._resolve_start_max_id(start_offset, init_max, table_options)

            # Already caught up to (or past) the init-time snapshot — stop.
            if start_max_id >= init_max:
                return {"max_id": init_max}

            end_max_id = min(init_max, start_max_id + max_records)
            return {"max_id": end_max_id}

        def get_partitions(
            self,
            table_name: str,
            table_options: dict[str, str],
            start_offset: dict | None = None,
            end_offset: dict | None = None,
        ) -> list[dict]:
            """Split the id range ``(start, end]`` into per-partition id windows.

            For batch reads (both offsets ``None``) the whole admission-controlled
            range from the resolved first id to the init-time snapshot is split.
            Each descriptor is ``{"start_id": a, "end_id": b}`` covering the
            half-open id range ``(a, b]`` — small and fully self-contained.
            """
            if table_name != ITEMS_TABLE:
                return []

            init_max = self._init_max_id()

            if start_offset is None and end_offset is None:
                # Batch mode: cover the full admission-controlled id range.
                start_max_id = self._resolve_start_max_id(None, init_max, table_options)
                end_max_id = init_max
            else:
                start_off = start_offset or {}
                end_off = end_offset or {}
                if start_off == end_off:
                    return []
                start_max_id = self._resolve_start_max_id(start_off, init_max, table_options)
                end_max_id = int(end_off.get("max_id", init_max))

            if end_max_id <= start_max_id:
                return []

            partition_size = self._partition_size(table_options)
            partitions: list[dict] = []
            lower = start_max_id
            while lower < end_max_id:
                upper = min(lower + partition_size, end_max_id)
                partitions.append({"start_id": lower, "end_id": upper})
                lower = upper
            return partitions

        def read_partition(
            self, table_name: str, partition: dict, table_options: dict[str, str]
        ) -> Iterator[dict]:
            """Fetch every item in the partition's ``(start_id, end_id]`` range.

            Runs on a Spark executor — self-contained, with its own session.
            Null responses (gap / deleted ids that return ``null``) are skipped.
            """
            if table_name != ITEMS_TABLE:
                return iter([])

            start_id = int(partition["start_id"])
            end_id = int(partition["end_id"])
            ids = range(start_id + 1, end_id + 1)  # half-open (start_id, end_id]
            records = self._fetch_items(ids, table_options)
            return iter(records)

        # ------------------------------------------------------------------
        # items helpers
        # ------------------------------------------------------------------
        def _max_records_per_batch(self, table_options: dict[str, str]) -> int:
            return int(
                table_options.get(
                    "max_records_per_batch", str(DEFAULT_MAX_RECORDS_PER_BATCH)
                )
            )

        def _partition_size(self, table_options: dict[str, str]) -> int:
            return int(table_options.get("partition_size", str(DEFAULT_PARTITION_SIZE)))

        def _fetch_concurrency(self, table_options: dict[str, str]) -> int:
            return int(
                table_options.get("fetch_concurrency", str(DEFAULT_FETCH_CONCURRENCY))
            )

        def _resolve_start_max_id(
            self,
            start_offset: dict | None,
            init_max: int,
            table_options: dict[str, str],
        ) -> int:
            """Resolve the exclusive lower bound (``max_id``) of the id range.

            Resolution order:
              1. A populated prior offset's ``max_id`` (resume from checkpoint).
              2. ``start_item_id`` table option — begin ingestion at that id, so
                 the exclusive lower bound is ``start_item_id - 1``.
              3. Default first-run bound: ``init_max - start_item_id_lookback``
                 (lookback default 1000) so a cold start does not read from id 0.
            """
            if start_offset and start_offset.get("max_id") is not None:
                return int(start_offset["max_id"])

            if "start_item_id" in table_options:
                return max(0, int(table_options["start_item_id"]) - 1)

            lookback = int(
                table_options.get("start_item_id_lookback", str(DEFAULT_START_LOOKBACK))
            )
            return max(0, init_max - lookback)

        def _fetch_items(
            self, ids, table_options: dict[str, str]
        ) -> list[dict]:
            """Fetch ``/item/{id}.json`` for each id, skipping nulls.

            Uses a bounded thread pool to fetch concurrently (the API documents no
            rate limit, but we stay polite with bounded concurrency). Results are
            returned in ascending id order so any downstream cursor logic sees a
            monotonic id sequence.
            """
            id_list = list(ids)
            if not id_list:
                return []

            concurrency = max(1, self._fetch_concurrency(table_options))
            session = self._new_session()
            results: dict[int, dict] = {}
            try:
                with concurrent.futures.ThreadPoolExecutor(
                    max_workers=concurrency
                ) as pool:
                    future_to_id = {
                        pool.submit(self._get_json, session, f"/item/{item_id}.json"): item_id
                        for item_id in id_list
                    }
                    for future in concurrent.futures.as_completed(future_to_id):
                        item = future.result()
                        if item is None:  # gap / deleted id — skip, do not emit
                            continue
                        item_id = item.get("id")
                        if item_id is None:
                            continue
                        results[int(item_id)] = item
            finally:
                session.close()

            return [results[i] for i in sorted(results)]

        def _read_items_sequential(
            self, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Sequential (single-driver) incremental read of ``items``.

            Mirrors the partitioned path's offset semantics so the connector still
            works when the framework reads ``items`` as a non-partitioned stream.
            Returns a moving end offset ``{"max_id": <last id read>}``; when the
            offset stops advancing (caught up to the init snapshot), the framework
            sees ``end_offset == start_offset`` and the trigger terminates.
            """
            init_max = self._init_max_id()
            max_records = self._max_records_per_batch(table_options)
            start_max_id = self._resolve_start_max_id(start_offset, init_max, table_options)

            # Defensive: maxitem may not have advanced — return cleanly.
            if start_max_id >= init_max:
                current = {"max_id": start_max_id}
                # Preserve the incoming offset exactly so the framework's
                # equality-based termination check fires.
                return iter([]), (dict(start_offset) if start_offset else current)

            end_max_id = min(init_max, start_max_id + max_records)
            ids = range(start_max_id + 1, end_max_id + 1)
            records = self._fetch_items(ids, table_options)
            end_offset = {"max_id": end_max_id}
            return iter(records), end_offset

        # ------------------------------------------------------------------
        # snapshot helpers
        # ------------------------------------------------------------------
        def _read_updates_snapshot(
            self, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read ``/updates.json`` as a single snapshot row.

            The endpoint returns ``{"items": [...], "profiles": [...]}``; we emit
            one row holding both arrays plus the run's snapshot timestamp. Snapshot
            reads carry no offset (return ``{}``).
            """
            session = self._new_session()
            try:
                payload = self._get_json(session, "/updates.json")
            finally:
                session.close()

            payload = payload or {}
            row = {
                "items": payload.get("items"),
                "profiles": payload.get("profiles"),
                "snapshot_time": datetime.now(timezone.utc).isoformat(),
            }
            return iter([row]), {}

        def _read_story_list_snapshot(
            self, table_name: str, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """Read a ``{top,new,best}stories.json`` array as one row per id.

            Each row carries the story id, its 0-based rank in the ranked list,
            and the run's snapshot timestamp. Full re-read each run; no offset.
            """
            endpoint = STORY_LIST_ENDPOINTS[table_name]
            session = self._new_session()
            try:
                ids = self._get_json(session, f"/{endpoint}.json")
            finally:
                session.close()

            ids = ids or []
            snapshot_time = datetime.now(timezone.utc).isoformat()
            records = [
                {
                    "story_id": int(story_id),
                    "rank": rank,
                    "snapshot_time": snapshot_time,
                }
                for rank, story_id in enumerate(ids)
            ]
            return iter(records), {}


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = HackerNewsLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_community_table_metadata"
    NAMESPACES_TABLE = "_community_namespaces"
    TABLES_TABLE = "_community_tables"
    VIRTUAL_TABLES = (METADATA_TABLE, NAMESPACES_TABLE, TABLES_TABLE)
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"
    NAMESPACE_PREFIX = "namespacePrefix"
    NAMESPACE = "namespace"


    def _decode_list_of_str_option(option_name: str, value: str | None) -> list[str] | None:
        """Decode and validate a JSON-encoded ``list[str]`` Spark option.

        Returns ``None`` if the option is absent; otherwise the parsed list.
        Raises ``ValueError`` with the offending value if the JSON is malformed
        or the decoded value is not a list of strings.
        """
        if value is None:
            return None
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, list) or not all(isinstance(s, str) for s in decoded):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded list[str]; "
                f"got: {decoded!r}"
            )
        return decoded


    def _decode_dict_option(option_name: str, value: str | None) -> dict:
        """Decode and validate a JSON-encoded ``dict`` Spark option."""
        if value is None:
            return {}
        try:
            decoded = json.loads(value)
        except json.JSONDecodeError as e:
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; "
                f"got non-JSON value: {value!r}"
            ) from e
        if not isinstance(decoded, dict):
            raise ValueError(
                f"option '{option_name}' must be a JSON-encoded dict; got: {decoded!r}"
            )
        return decoded


    # PySpark's DataSource API requires camelCase method names and inherits
    # semantics from the parent class, so per-method docstrings are redundant.
    # pylint: disable=invalid-name,missing-function-docstring
    class LakeflowStreamReader(SimpleDataSourceStreamReader, SupportsTriggerAvailableNow):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowPartitionedStreamReader(DataSourceStreamReader, SupportsTriggerAvailableNow):
        """Proxy that bridges SupportsPartitionedStream to PySpark's DataSourceStreamReader.

        Used when a connector implements the SupportsPartitionedStream mixin to
        support partitioned streaming reads across Spark executors.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self.table_options = {k: v for k, v in options.items() if k != IS_DELETE_FLOW}

        def initialOffset(self):
            return {}

        def getDefaultReadLimit(self):
            # Admission control is the connector's responsibility (e.g. via
            # window_days, max_records_per_batch), not the engine's.  Always
            # ask the engine for ReadAllAvailable.
            return ReadAllAvailable()

        def latestOffset(self, start: dict, limit) -> dict:
            # We declared ReadAllAvailable via getDefaultReadLimit; the engine
            # must respect it.  Anything else means admission-control expectations
            # we do not support — fail loudly rather than silently ignore.
            if not isinstance(limit, ReadAllAvailable):
                raise ValueError(
                    f"LakeflowPartitionedStreamReader only supports ReadAllAvailable; "
                    f"got {type(limit).__name__}. Micro-batch sizing must be controlled "
                    f"by the connector implementation (table_options), not the engine."
                )
            return self.lakeflow_connect.latest_offset(
                self.table_name, self.table_options, start
            )

        def partitions(self, start: dict, end: dict):
            partition_descs = self.lakeflow_connect.get_partitions(
                self.table_name, self.table_options, start, end
            )
            return [InputPartition(json.dumps(p)) for p in partition_descs]

        def read(self, partition: InputPartition):
            partition_desc = json.loads(partition.value)
            records = self.lakeflow_connect.read_partition(
                self.table_name, partition_desc, self.table_options
            )
            return map(lambda x: parse_value(x, self.schema), records)

        def prepareForTriggerAvailableNow(self) -> None:
            # No need to do anything special here. Everything is handled in the __init__ method.
            pass


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]
            self._supports_partition = isinstance(lakeflow_connect, SupportsPartition)

        def partitions(self):
            if self._supports_partition and self.table_name not in VIRTUAL_TABLES:
                try:
                    partition_descs = self.lakeflow_connect.get_partitions(
                        self.table_name, self.options
                    )
                    return [InputPartition(json.dumps(p)) for p in partition_descs]
                except Exception:
                    self._supports_partition = False
            return [InputPartition(None)]

        def read(self, partition):
            if self.table_name == METADATA_TABLE:
                records = self._read_table_metadata()
            elif self.table_name == NAMESPACES_TABLE:
                records = self._read_namespaces()
            elif self.table_name == TABLES_TABLE:
                records = self._read_tables()
            elif self._supports_partition and partition.value is not None:
                partition_desc = json.loads(partition.value)
                records = self.lakeflow_connect.read_partition(
                    self.table_name, partition_desc, self.options
                )
            else:
                records, _ = self.lakeflow_connect.read_table(self.table_name, None, self.options)
            return map(lambda x: parse_value(x, self.schema), records)

        def _read_table_metadata(self):
            table_names = _decode_list_of_str_option(
                TABLE_NAME_LIST, self.options.get(TABLE_NAME_LIST)
            ) or []
            table_configs = _decode_dict_option(
                TABLE_CONFIGS, self.options.get(TABLE_CONFIGS)
            )
            all_records = []
            # Preserve caller-supplied table order — caller controls it.
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records

        def _read_namespaces(self):
            # Connectors without SupportsNamespaces are flat — no rows.
            if not isinstance(self.lakeflow_connect, SupportsNamespaces):
                return []
            prefix = _decode_list_of_str_option(
                NAMESPACE_PREFIX, self.options.get(NAMESPACE_PREFIX)
            )
            namespaces = self.lakeflow_connect.list_namespaces(prefix)
            # Sort framework-side for deterministic output regardless of
            # connector iteration order.
            return [{"namespace": ns} for ns in sorted(namespaces)]

        def _read_tables(self):
            namespace_supplied = NAMESPACE in self.options
            if isinstance(self.lakeflow_connect, SupportsNamespaces):
                if not namespace_supplied:
                    raise ValueError(
                        f"option '{NAMESPACE}' is required when reading "
                        f"'{TABLES_TABLE}' against a connector that implements "
                        f"SupportsNamespaces. Pass a JSON-encoded list[str] "
                        f"(use '[]' for root-level tables; walk the tree via "
                        f"'{NAMESPACES_TABLE}' to enumerate every namespace)."
                    )
                namespace = _decode_list_of_str_option(
                    NAMESPACE, self.options[NAMESPACE]
                )
                tables = self.lakeflow_connect.list_tables_in_namespace(namespace)
                return [
                    {"namespace": namespace, TABLE_NAME: tn}
                    for tn in sorted(tables)
                ]
            # Flat connector path. Reject a stray `namespace` option — the
            # caller probably mistook this connector for namespace-aware and
            # silently ignoring the option would mask the bug.
            if namespace_supplied:
                raise ValueError(
                    f"option '{NAMESPACE}' was supplied but the connector does "
                    f"not implement SupportsNamespaces. Either omit the option "
                    f"or use a namespace-aware connector."
                )
            return [
                {"namespace": [], TABLE_NAME: tn}
                for tn in sorted(self.lakeflow_connect.list_tables())
            ]


    class LakeflowSource(DataSource):
        """
        PySpark DataSource base for Lakeflow Connect.

        Two ways the connector implementation is bound:

        - Per-source subclass (wheel / multi-file deployment): subclass and set
          ``_lakeflow_connect_cls``::

              class GmailDataSource(LakeflowSource):
                  _lakeflow_connect_cls = GmailLakeflowConnect

              spark.dataSource.register(GmailDataSource)

        - Merged single-file deployment (SDP): ``_lakeflow_connect_cls`` is left
          ``None`` and the connector is taken from the module-level
          ``LakeflowConnectImpl`` placeholder, which the merge script substitutes
          with the actual implementation class.
        """

        # Per-source subclasses set this. Left ``None`` on the base so the merged
        # single-file path falls back to the ``LakeflowConnectImpl`` placeholder.
        _lakeflow_connect_cls = None

        # Spark format name. Defaults to "lakeflow_connect" because Unity Catalog
        # connection-option injection looks for that exact string. A per-source
        # subclass may override this with its source name once it no longer relies
        # on UC injection (see the commented override in each source's __init__.py).
        _format_name = "lakeflow_connect"

        def __init__(self, options):
            self.options = options
            table = options.get(TABLE_NAME)
            # Catch typos against the framework's reserved virtual-table namespace
            # early — falling through to the connector with an unknown
            # `_community_*` name yields a confusing per-connector error.
            if table and table.startswith("_community_") and table not in VIRTUAL_TABLES:
                raise ValueError(
                    f"unknown framework virtual table '{table}'. Valid framework "
                    f"virtual tables are: {', '.join(VIRTUAL_TABLES)}. "
                    f"For a regular source table, use a name that does not start "
                    f"with '_community_'."
                )
            # Per-source subclasses bind the implementation via _lakeflow_connect_cls.
            # The merged single-file path leaves it None and relies on the
            # LakeflowConnectImpl placeholder (substituted by the merge script).
            connect_cls = type(self)._lakeflow_connect_cls or LakeflowConnectImpl
            self.lakeflow_connect = connect_cls(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return cls._format_name

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            if table == NAMESPACES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                    ]
                )
            if table == TABLES_TABLE:
                return StructType(
                    [
                        StructField("namespace", ArrayType(StringType()), False),
                        StructField(TABLE_NAME, StringType(), False),
                    ]
                )
            return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def streamReader(self, schema: StructType):
            # Use the partitioned DataSourceStreamReader when the connector
            # implements SupportsPartitionedStream and the table opts in.
            # Otherwise, delegate to super() which raises PySparkNotImplementedError,
            # causing Spark to fall back to simpleStreamReader().
            if isinstance(self.lakeflow_connect, SupportsPartitionedStream):
                table = self.options[TABLE_NAME]
                if self.lakeflow_connect.is_partitioned(table):
                    return LakeflowPartitionedStreamReader(self.options, schema, self.lakeflow_connect)
            return super().streamReader(schema)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
